### ISSUE TITLE
Tech/civic popup appears for a split second even when Disabled

### ISSUE THREAD

**Issue by exo66** [civfanatics/CQUI_Community-Edition#169]
macOS 10.15.5, Mac app store version. cqui current GitHub master branch. it happens with only cqui installed, and no settings changed.

[infixo copied from the title]
tech/civic popup seems to appear for a split second even though its not supposed to show up by default

**Comment by the-m4a** [comment]
Ok yeah, I see this too.  Good to know I'm not going crazy.  I think this is new after the recent patch, maybe something changed from Firaxis.  Anyway, looking into it.

**Comment by the-m4a** [comment]
It's the standard popup window you see when completing research on a tech or civic -- middle of the screen, "Research Complete" etc.  It appears very briefly, and while there were no changes on the CQUI side recently, the mechanism used by CQUI to hide that popup was likely not the correct way to go about it.  In looking last night I was not able to figure a way to keep the popup hidden _and_ still play the audio that reads the quote.

In TechCivicCompletedPopup.lua, the CQUI change is in RealizeNextPopup, where after the rest of the code has done the work to populate the properties that would appear on the popup (ShowTechCompletedPopup), CQUI just hides the thing by calling UIManager:DequeuePopup.

The popup itself is "Queued" in AddCompletedPopup:
```
UIManager:QueuePopup( ContextPtr, PopupPriority.Low, { DelayShow = true });
```

My assumption is that prior to the recent set of changes from Firaxis, there was enough going on in the background that this low priority popup would end up not showing on screen by the time CQUI called DequeuePopup in the RealizeNextPopup function.  Now that popup will appear very briefly - less than half a second on my machine.

I tried preventing the QueuePopup, which results in the popup not appearing, but also no audio plays because RealizeNextPopup no longer gets called as a result.

**Comment by Infixo** [comment]
What’s the point of having an audio without a popup? This doesn’t make much sense imho. Also, is there an option to actually disable a window and enable audio? I thought that the “disable popup” is meant for both.

**Comment by the-m4a** [comment]
Yes - CQUI_TechPopupVisual and CQUI_TechPopupAudio; visual defaults to false while audio defaults to true.  There's a notification message when civic or research is completed, so I guess the idea was those two things pair together.  Existing design, so I'm not sure what the thoughts were behind it.

**Comment by the-m4a** [comment]
No problem.  Assuming it pastes (as it's 6mb), I used ScreenToGif to show exactly what happens (recorded at 15FPS, to save on size):
![image](https://i.imgur.com/6bxcDhk.gif)

The CQUI version of TechCivicCompletedPopup.lua has minimal differences between it and the current version in game.  There were no changes to this file recently, and this did not start occurring until the most recent patch _or_ one of the recent CQUI changes is somehow affecting this (WorldTracker change?)... either way, it's a recent happening.

The mechanism of "QueuePopup then update Popup data" is Firaxis design, something that exists in the unmodified game.  While not as obvious, the issue of showing the popup before it's been updated is present in the unmodified game, as the previous tech very briefly shows before the Popup is updated and resized.  
For example: you can see in this screenshot from ScreenToGif that for a single 33ms frame, the previous tech Military Science is visible, before the control is updated to show the tech just discovered (Scientific Theory).
![image](https://user-images.githubusercontent.com/8787640/92219417-66a2e500-ee4f-11ea-9450-a5ef5f8efb08.png)

It's barely noticeable, but noticeable nonetheless, and I assume more noticeable on slower machines.  I recorded this gif at 60FPS, so it's really short gif, but you can just see it.  It's kind of a jarring visual so I'll just link it: [PopupIssue](https://i.imgur.com/d4vpfVS.gif)

**Comment by Infixo** [comment]
My proposition is the following.
a) The option "popup enable/disable" should do exactly what it says - either popup is shown or not. If chosen NO then the popup should be disabled before queing (i.e. QueuePopup is never called). Simple and clean.
b) The audio option should also do what it says - when the popup is shown then switch off the sound. Many people complained about Sean Bean and wanted him gone as much as possible. I suppose that was the idea behind this option. Already implemented, no change here is needed.
That's it.

The option "sound without window" simply doesn't make sense and there is no point trying to maintain it. E.g. imagine 3 techs finishing at the same time (due to boosts, etc.) You should then hear 3 quotes at the same time overlapping with each other. Absurdly stupid. Because there is no way to control over when they start. That is why audio is tight to the popup in the first place. So - no popup = no audio. Also simple.

**Comment by the-m4a** [comment]
I agree that if we tie hiding the popup with also losing the audio, we should simply not queue it.  I kind of like the audio - or at least, don't mind it, and will leave it on when I play with sound.  I haven't been on CivFanatics or Reddit enough to know whether I'm in the minority there, but I'll take your word for it.

I'm not following you on "the audio option should do what it says".
![image](https://user-images.githubusercontent.com/8787640/92300087-ee9af480-ef0c-11ea-92f5-546ddaa1d727.png)

The Sean Bean voiceover is enabled by default in the CQUI settings.  The audio should play when the popup is enabled.  If the Play Civic/Tech audio quote is disabled, then it should only play when someone clicks on the quote in the popup UI.

The audio also does not overlap - whenever UI.PlaySound is called, it stops whatever happened to be playing at the time - at least when called from the FireTuner.  I assume this would translate to the lua module, and if 3 techs were discovered at once only the audio from the last one would play.

```
> techType = GameInfo.Technologies[1].TechnologyType
> results = DB.Query("SELECT Quote, QuoteAudio from TechnologyQuotes where TechnologyType = ? ORDER BY RANDOM() LIMIT 1", techType);
> audio = nil
> for i, row in ipairs(results) do audio = row.QuoteAudio; break; end
> audio
Play_Animal_Husbandry_Quote_1
> UI.PlaySound(audio)
> UI.PlaySound(audio)
```

**Comment by Infixo** [comment]
Thanks for providing some more info.
I wasn’t sure what happened when more than 1 sound is queued.

a) “do what it says” bad wording maybe. Option says “popup audio”. There is no SEPARATE popup for an audio. There is only ONE popup. So for me it means “audio that plays when the popup appears”. No popup, no audio.
B) thanks for checking multiple quotes. That only proves my point. Separate audio is pointless as you will only hear the last quote.

**Comment by Infixo** [comment]
As a separate note - I always play with tech popups enabled. Disabling them saves so little time compared to the entire game that is pointless imho. Finishing a tech or civic is a pretty important event in the game and this kind of extra attention is useful.
If I don’t want to see it, I just press ESC.

**Comment by the-m4a** [comment]
Yeah I was curious on the last one because I couldn't remember if it did or not.  I didn't think it did, but also didn't know offhand what mechanism existed to ensure it didn't.  I'm kind of surprised it actually requires a "real" audio clip of some sort to stop the sound - UI.PlaySound("Stop_Speech_Tech") stops it, while UI.PlaySound("foo") does not.

Also - treating it as "automatically play the audio with the popup" makes more sense than having the audio be completely independent.  While I didn't mind the voiceover playing without the popup, it's also not my favorite CQUI feature by any means. 
 I'm curious if removing that "feature" will generate any grumbling...I guess we can find out

I'll update the PR.  I wouldn't mind other opinions on this, but the code changes are easy enough that if for some reason there's clamoring to maintain the current design, it can be updated easily to do so

**Comment by Infixo** [comment]
So, to be clear, we basically go with my proposition, i.e.
a) hook into notification, so the popup will never be even queued in the first place
b) audio on/off only when popup is enabled

**Comment by Infixo** [comment]
> Yeah I was curious on the last one because I couldn't remember if it did or not. I didn't think it did, but also didn't know offhand what mechanism existed to ensure it didn't. I'm kind of surprised it actually requires a "real" audio clip of some sort to stop the sound - UI.PlaySound("Stop_Speech_Tech") stops it, while UI.PlaySound("foo") does not.

It is actually a quirk from WWise engine which handles all sound and audio. It works like sort of one-way mixer. E.g. you just insert sounds there and it plays them. All sound-related things happen in the engine and there is really no control from e.g. Lua. There is no API for it, etc. So, to stop the sound a trick needs to be used.

**Comment by the-m4a** [comment]
yeah - for
for a) use the same logic that the blocked_by_tutorial does.  Popup is never "built" and queued in that case.
and b) it becomes "automatically play the audio when popup shows"

**Comment by wayneb64** [comment]
> Yeah I was curious on the last one because I couldn't remember if it did or not. I didn't think it did, but also didn't know offhand what mechanism existed to ensure it didn't. I'm kind of surprised it actually requires a "real" audio clip of some sort to stop the sound - UI.PlaySound("Stop_Speech_Tech") stops it, while UI.PlaySound("foo") does not.
> 
> Also - treating it as "automatically play the audio with the popup" makes more sense than having the audio be completely independent. While I didn't mind the voiceover playing without the popup, it's also not my favorite CQUI feature by any means.
> I'm curious if removing that "feature" will generate any grumbling...I guess we can find out
> 
> I'll update the PR. I wouldn't mind other opinions on this, but the code changes are easy enough that if for some reason there's clamoring to maintain the current design, it can be updated easily to do so

I have read this thread a few times and I am sorry I am not sure what exactly you are talking about removing but the way I play is with popup only, no audio, so I hope you are not suggesting removing that as an option. iow I should not have to listen to the audio if I want to see the popup.

**Comment by Infixo** [comment]
@wayneb64 It will still be possible.
What will be possible: popup with audio (standard), silent popup, no popup (and no audio).

**Comment by wayneb64** [comment]
Perfect, silent popup is the option that is important to me.

**Comment by Infixo** [comment]
Fixed.
