### ISSUE TITLE
Policy Pop-Up reminder shouldn't show on first turn for Barbarossa

### ISSUE THREAD

**Issue by stagnate** [civfanatics/CQUI_Community-Edition#195]
**Describe the bug**
If playing as Barbarossa (with free military policy), the Policy Pop-Up reminder shows up at the end of the first turn.  However, the player doesn't have any policies unlocked yet so they don't have a government screen.

It can easily be worked around by closing the window and clicking next, or disabling the Pop Up Reminder, but the 'Change Government' dialog box doesn't work.

**Comment by the-m4a** [comment]
Would this happen if CQUI is not loaded?  One of these days the energy currently drained by work will lessen and I can rededicate some time back to CQUI

**Comment by the-m4a** [comment]
I remember looking at this once upon a time though I don't remember all of the details.  What I *do* remember is that "Change Government" on that button is the default text that is set in the XML, and whenever that button is meant to be shown, the text is changed to either "Government Unlocked" or "Change Policies".

This is using the defaults for the Icons and strings on the buttons as set in the policyreminderpopup.xml file:
![image](https://user-images.githubusercontent.com/8787640/97961178-b1fe4480-1d67-11eb-8d68-8b31159015e7.png)

In the FireTuner, I can manipulate the object (changing text and whatnot) only when in the PolicyReminderPopup Lua state.  If I pick the TechCivicCompletedPopup state, changes do not affect this on-screen object.

**Comment by the-m4a** [comment]
posting that because i thought it interesting, shortly thereafter I think I found the bug:
In actionpanel.lua:
```lua
   local PRD:table    = pPlayer:GetCulture()
    if (PRD:CivicCompletedThisTurn() and PRD:GetCivicCompletedThisTurn() ~= futureCivicIndex and not PRD:PolicyChangeMade()) then
```

It appears for whatever reason, CivicCompletedThisTurn() returns as TRUE, while GetCivicCompletedThisTurn returns -1.  That -1 is bad and should be checked - as over in policyreminderpopup.lua, all of the changes in appearance made to that Policy Reminder dialog happen after these two lines:

```lua
function ShowPolicyReminderPopup(player:number, civic:number)
    local civicInfo:table = GameInfo.Civics[civic];
    if civicInfo ~= nil then
```

When this function is called, "civic" is -1, the value returned by GetCivicCompletedThisTurn().
