### ISSUE TITLE
Note for tech/civic progress - one turn away from maximum inspiration bonus, CQUI and other mods

### ISSUE THREAD

**Issue by Sorxus** [civfanatics/CQUI_Community-Edition#201]
Besides CQUI I use also other 13 mods without altering the rules of game and I was confused because I missed note for tech/civic about one turn away from maximum inspiration bonus (for current version 1.0.6.9 and one before, 1.0.5.11, I couldn't say if it was such behavior in versions before). All mods are up-to-date.
So I tried with only two mods at the time, CQUI and another one and I can report my conclusions:

Note for tech/civic progress IS visible when using CQUI +:
- Infixo's Better Civilopedia,
- Infixo's Better Climate Screen,
- Infixo's Better Leader Icon,
- Infixo's Better Loading Screen,
- Infixo's Better Religion Window,
- Infixo's Better Report Screen,
- Infixo's Better World Rankings,
- Infixo's Real Era Tracker,
- Infixo's Real Great People,
- Infixo's Real Governor Inspector,
- Sukritact's Global Relations Panel.

Note for tech/civic progress IS NOT visible when using CQUI + one of those two:
- Infixo's Better Tech Tree,
- Sukritact's Simple UI Adjustment.

Another small thing, there is typo in note for tech/civic progress, there is unwanted space between tech/civic name and comma:

![Brez naslova](https://user-images.githubusercontent.com/37362600/98528237-53abf700-227c-11eb-80e9-b43bb5f76251.jpg)
 
To easier find right moment when should notes appear here is game save, just end turn and notes should appear.

[BASIL II 163 170 BC-Note Test.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5509670/BASIL.II.163.170.BC-Note.Test.zip)

**Comment by Infixo** [comment]
The issue is caused by Better Tech Tree and I am aware of it. 
Basically, BTT was designed and implemented to work with a full replacement of Tech and Civic Trees, and it was ok as long as CQUI was replacing both. But some time ago (a month or two), the CQUI started using extensions, so now BTT needs to account for that fact, It is fairly easy, I just don't have time to do it properly.
And I am aware of all of this because I did the "extension" change in CQUI myself with the goal of eventually changing BTT as well :)

**Comment by Infixo** [comment]
If you are willing to try the quick workaround, then go to TechTree_BTT_Base.lua and CivicsTree_BTT_Base.lua in BTT and find these lines at the top:
include("TechTree");
include("CivicsTree");
Then change them to
include("TechTree_CQUI");
include("CivicsTree_CQUI");
respectively.
This will cause BTT to load a proper extension from CQUI instead of vanilla base files.

**Comment by Sorxus** [comment]
I tried with your workaround, modified TechTree_BTT_Base.lua and CivicsTree_BTT_Base.lua in BTT as you instructed:

![Capture](https://user-images.githubusercontent.com/37362600/99817034-b179f200-2b4c-11eb-8a7c-984d606316c4.JPG)

... and I have to report that it didn't solved this problem, game with CQUI + Better Tech Tree still doesn't show note about tech/civic progress.

**Comment by Sorxus** [comment]
Correct, with newer version of BTT (v.3.2) is issue with CQUI and BTT (one turn away note) solved.
