### ISSUE TITLE
Investigate: Damaged Holy Sites not repairable?

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#23]
Issue from the Workshop comments feed (via carlageek):

Tried CQUI for the first time on a fully updated Civ VI with all add-ons, NFP, etc. It looks terrific and I'm excited about all the improvements. But I have run into some bugs.
* I pillaged a Holy Site and then captured the city. The site now shows as pillaged on the map, but in the production queue there is no option to repair it. (The production screen has a checkmark by the holy site as though it's complete, and also lists Synagogue, though it says I can't build a Synagogue because I have no temple. But I can't build a temple because the site is pillaged!)
* This one is only cosmetic, unlike the previous one, but I missed my chance to get the last Great Prophet, and now the prophet column in the Great People screen is showing a bunch of placeholder strings like X/Y and so on.
I can provide a save if needed, but I'm not sure how. Is there a better way to report these bugs? Thanks again for maintaining such a useful mod as the game evolves.

**Comment by Infixo** [comment]
@the-m4a Can you get the save file for this issue?

**Comment by Infixo** [comment]
Here is a savefile with a pillaged Holy Site. Everything works ok. 
[Uploading JADWIGA 63 dmghs.zip…]()

(a) The incident mentions however that there is a Checkmark on it. The **only** situation when the checkmark is put is when the district is not considered pillaged by the production panel. And this means that Lua function returned "not pillaged". There is no processing, no changes, very simple code. That would mean a bug in the DLL - rather not possible, this functionality is too important.
(b) Also, CQUI doesn't do anything to the pillage status (it is a Repair field in the item data). All goes via vanilla files.

a+b means that most likely there is some mod conflict. Maybe some old files from other mods or older CQUI versions. The person who raised that should disable all mods and make sure that there is no issue, then toggle only cqui and see if the issue is still there.

**Comment by the-m4a** [comment]
Thanks for looking at this.  I had also not observed any issues but hadn't looked in depth as of yet.  We can close this.
