### ISSUE TITLE
Rename top-level branch to "main"

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#239]
Hey @alexeyOnGitHub - I can't figure out how to just send you a message to ask: can we designate the default branch as main?  I ask because of a few reasons: many folks' [association of the word "master"](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main), and we made this change at work and I like the consistency of all things point to main. 
It's true that Git has stated it was [never intended in that context](https://git.github.io/rev_news/2020/07/29/edition-65/), I think this kind of change not a bad thing to do.

I created the branch, but I can't designate it as the default as I do not have the permissions to do so (as best I can tell).  If you're okay with the change, I would appreciate it!

Thanks!

**Comment by alexeyOnGitHub** [comment]
I updated the default branch for this repo to be "main". we can delete the old one some time later when we confirm the new one is working fine. there are no auto-builds or other processes attached to this repo, so I do not expect this to be a problem.

note - there was also an option to rename the old branch to whatever, but given that you already created a new branch ("main"), I **updated the repo** to use that one as default, **instead of renaming** the old one.

**Comment by alexeyOnGitHub** [comment]
let me know if you prefer me to just drop "main" branch and rename the old "master" to "main" instead.

**Comment by the-m4a** [comment]
That would work as well - I have no attachment to that new instance of main.  And thanks!

Sent from my iPhone

On Jan 26, 2021, at 2:53 PM, Alexey <notifications@github.com> wrote:

﻿

let me know if you prefer me to just drop "main" branch and rename the old "master" to "main" instead.
