### ISSUE TITLE
Please show the boundary of the city

### ISSUE THREAD

**Issue by realliyifei** [civfanatics/CQUI_Community-Edition#303]
1. When clicking the city, the unimproved tiles and mountains are not showed and sometimes it's confusing which tiles belong to which cities using this mod. Showing the boundary of the city as the original system did may be a good solution.

2. Also, as you can see, the expanding territory (the purple one) doesn't contain the number of turns needed here, though it does show when hovering on the city name. Not sure whether it's caused by this mod though.

3. Not sure whether it's possible, but it's better to have the map shows next to the left panel so that it's fully accessible. I prefer to view the map when managing the cities because location heavily matters. 

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/32441766/118876778-a580aa00-b8bb-11eb-9c65-8009c3adc222.png">

**Comment by the-m4a** [comment]
The boundary is shown, short of: the hexes that are lighter (not orange) than others are part of the selected city, while those that are darker belong to another city and/or have a district placed upon them.  I have been looking a lot at the lens stuff lately so I'll see if there's something I can add that would make this more obvious.

The number of turns until expansion not showing on the purple hex is because that hex is outside the normal boundaries of the city (more than 3 hexes away).  I can look and see if there's logic that controls that, but I'm not sure it's terribly useful in this situation?

The minimap is a different situation.  It may be possible to move it, but haven't looked into it and it gets complicated with the varying size of the map and the other controls that appear when clicking on a city.  That'd be a longer-term project kind of thing.

**Comment by the-m4a** [comment]
I went and looked at this one last night and it turned out this wasn't as difficult as I thought it might be.  And so far, I think I like the results.  I'm going to post a PR shortly that:
- Shows the city boundaries
- Adds an "other" color to tiles owned by the city that do _not_ have a citizen associated with it (like certain districts and mountains)
- Moves the mini-map over when showing a city (hiding the buttons that do things it shouldn't)

In this image my mouse cursor is hovering over the banner for Jenne, you can see the borders of the city and the "owned" but not used tiles.
![image](https://user-images.githubusercontent.com/8787640/121769095-8e2d8900-cb16-11eb-8ffe-6afd6fcff6b1.png)

And here, I've clicked on Jenne to show the City Management page, which also moved the Minimap over... which I keep thinking, that's alright!  I hid the buttons that interfere with the City View (other lenses, map pins, CQUI settings), left those that can be useful while in this view (search, plot settings, map-type toggle).
![image](https://user-images.githubusercontent.com/8787640/121769147-d51b7e80-cb16-11eb-9305-8793b9d31b11.png)

**Comment by realliyifei** [comment]
Thanks. That's really helpful!
