### ISSUE TITLE
need to document the release process

### ISSUE THREAD

**Issue by alexeyOnGitHub** [civfanatics/CQUI_Community-Edition#4]
let's add a file explaining how to release the mod to Steam.
is some build stage required? validation, compilation, etc?
do you have to use Civ 6 Development Tools / Workshop uploader UI? are there any scripts that we can set up in Jenkins? etc
I launched the Workshop Uploader  on Win 10 and it consistently crashes when I open the current CQUI modinfo file.

**Comment by alexeyOnGitHub** [comment]
@Azurency  hey, can you please share a few notes?

**Comment by the-m4a** [comment]
User named skrepsky found an issue with an XML comment, posted a pull request to the version in my repo.  I integrated that change (it was literally <! -- instead of <!-- ... it was surprising it didn't tank the game).

I am in the process of putting together the artifacts from the Workshop posting, and will post it to my steam workshop page for review.  I will also post a PR here with that stuff.  

I am going to explore whether or not we need to change the mod ID guid in order to publish it.  My guess is that we need to do so.

**Comment by the-m4a** [comment]
I created a PR, which includes info on the release process.  I also uploaded the game to steam (https://steamcommunity.com/sharedfiles/filedetails/?id=2115302648).  I'm curious if I can list you as a contributor and have you also do an upload, which would affect the same published workshop item.  I'm not positive we can have multiple folks have the ability to do uploads, but it would be nice.

**Comment by alexeyOnGitHub** [comment]
thank you for fixing the mod and uploading it! this affects hundreds of people. do you want to create a post on Civfanatics forum with a link to the new plugin location on Steam?

I did not find any info on how to set up automated release process via scripts. we can use the Uploader UI for now. I would much rather prefer an automated Jenkins build that would
* validate the changes (check syntax, compile files, whatever)
* upload the required files
* push a notification to proper channels, maybe including Civfanatics forum and such

**Comment by the-m4a** [comment]
I'm with you on that - automated updates, etc.  I'll go post a thread on CivFanatics and Reddit, and make a comment in the existing mod.
