### ISSUE TITLE
Seasteads are not counted for housing

### ISSUE THREAD

**Issue by Infixo** [civfanatics/CQUI_Community-Edition#42]
I am playing a late game and noticed that after putting 4 seasteads there was no increase in Housing in the city. It was showing 31. I disabled CQUI and the vanilla interface shows a correct value of 39.
Also, I may add that Better Report Screen also shows the correct value, so the issue is the routine in CQUI that calculates housing from improvements.

**Comment by alexeyOnGitHub** [comment]
I expected CQUI to reuse the calculation function from the base game, and show the results in some improved UI. if CQUI includes code to calculate housing and everything else, that sounds like a huge maintenance burden. I suppose reusing that code from the base game is not possible? otherwise it would have been done already.

**Comment by Infixo** [comment]
The reason is explained in #34

**Comment by Infixo** [comment]
You can use my code from #34, if you want. It is working. Just leave the comment with my name.

**Comment by the-m4a** [comment]
Of course! Appreciated.  Your code effectively replaces the entirety of the CQUi-getrealhousing function, right?

I created a branch for this yesterday and have been working to do the extend/replace instead of replacing the entire file.  I am also hoping to put this logic in a common file instead of having to duplicate it for each expansion file.

**Comment by Infixo** [comment]
Well, not entire exactly. In cqui there is some event handling at the end. And my code just takes city as an argument, cqui takes 3 params, so check what they are used for exacly.

**Comment by alexeyOnGitHub** [comment]
submitted #48 as a starting point to discuss ways to improve reusability of our code.

**Comment by SmithsonianDSP** [comment]
To understand correctly, is the **_sole_ ** reason for calculating housing separately just to determine if the housing is `x.5` or `x.0`? 

If so, then would it be more prudent to just use the game's own housing function and then determine if there should be a `.5` or not?  This would possibly save from having to factor in all of the other aspects involved. This way, worst-case scenario, the housing calculation is only off by 0.5. 

Alternatively—or in addition to—you could compare the resulting housing calculation against the game's as a sanity check and, if they differ more than 1.0, fall back to showing the game's value in the UI (maybe prefix it with `~` to indicate that the half-housing calculation isn't known).

**Comment by Infixo** [comment]
@SmithsonianDSP To be precise, to determine if the housing is x.0 or x.y. The game’s routine just returns an integer part. The remainder is atm always 0.5 because there are only “2 tiles required” cases, but is possible to create cases like 2 housing for 3 improvements.
Anyway, in #34 I proposed the same approach as you described.

**Comment by the-m4a** [comment]
Still working on this - I have the extension file working for expansion2, got a few things cleaned up and done correctly tonight.  
While I'm in here I'm going to move the CityStrike button to above the banner because I tire of not being able to hit the button when I have another unit in the city

![image](https://user-images.githubusercontent.com/8787640/85270640-75702300-b42e-11ea-95fa-776fb47a07fd.png)

**Also**, based on what the basegame returns for the Mayan farms, it seems the bonus is +1 housing in addition to the 0.5 housing farms already give.  For example when there's 2 farms for a Mayan city, the basegame will report 3 housing from improvements... so that's fixed here:
![image](https://user-images.githubusercontent.com/8787640/85270832-c3852680-b42e-11ea-97a5-b6fa11c6f803.png)

Also updated the tooltip to show 1.5 housing for the Maya builder
![image](https://user-images.githubusercontent.com/8787640/85270959-f4fdf200-b42e-11ea-9e1d-d0a567042ff8.png)

**Comment by alexeyOnGitHub** [comment]
@the-m4a I think moving the bombardment button is an interesting idea, but let's keep that in a separate feature branch? we can review and merge that one independently from the housing changes.

**Comment by the-m4a** [comment]
Yep, no problem.  It is a fairly easy change - small chunk of code isolated to a single function.  Hoping to turn this into a full PR today or tomorrow, didn’t have as much time as I thought I would over the weekend

**Comment by Infixo** [comment]
Seasteads are fixed, so I can close this. Anyone wants to leave it open for some reasons?

**Comment by the-m4a** [comment]
I just realized I haven't uploaded the changes yet - leave it open until I update the files on the workshop

**Comment by the-m4a** [comment]
It's been uploaded, closing this issue
