### ISSUE TITLE
Restore Improvement recommendations when a builder is selected

### ISSUE THREAD

**Issue by hondrus31** [civfanatics/CQUI_Community-Edition#46]
**Describe the bug**
I tried to reactivate the improvements recommendation for the builder view (which is disabled by default), but no icon shows up on map. I tried disabling other mods but it won't fix the issue. Disabling CQUI does restore the recommendation icon.
I'm running the Vanilla Epic Games store version, the one they gave it away for free.

**To Reproduce**
-Go to CQUI menu
-Recommendation tab
-Toggle "Show Improvements Recommendation" (third option) 
-No recommendation icon shows up on map

**Expected behavior**
Recommendation icon should show up, as it would without CQUI mod.

**Screenshots**
![image](https://user-images.githubusercontent.com/58083279/85066329-0e910680-b1af-11ea-9db9-0b202355a34c.png)
![image](https://user-images.githubusercontent.com/58083279/85066383-24063080-b1af-11ea-836f-a1ea64dc6af0.png)

**General informations**
 - OS: Windows 10 Pro x64
 - Version 1.0.1.501 (504666) DX12- Epic Games store
 - No expansions
 - Other mods: 
1. Better Civilopedia
2. Better Leader Icon
3. Better Loading Screen
4. Better Report Screen
5. CQUI
6. Real Great People
7. Real Strategy
8. Real Tech Tree

 
**Save game and logs**
[bugattachments.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/4800966/bugattachments.zip)

**Comment by Infixo** [comment]
@hondrus31 ShowImprovementsRecommendations option was actually coded to toggle on/off the extra icon that appears in the Unit Panel on top of the possible builds. It is active on your screenshot, it shows the Farm.
For reasons unknown to me, the recommendations on the tiles were simplt turned off completely, regardless of this setting. I am not even sure if there ever was such a feature, because there is not code for that at all.
Anyway, I added this feature. Toggling on/off those recommendations also work for the city view.

**Comment by hondrus31** [comment]
Oh, I didn't realize it wasn't supposed to do it. Well, thank you very much, I tested it and it work flawless.
