### ISSUE TITLE
Amenities difference in City Banner

### ISSUE THREAD

**Issue by Sorxus** [civfanatics/CQUI_Community-Edition#90]
At the moment there is in City Banner "Turns until growth" number, "Housing Difference" and "Turns until border growth" (with 10 July 2020). 
Wouldn't be good to have also "Amenities difference" number in fourth corner of city population circle?

**Comment by Infixo** [comment]
If your city needs amenities, there is a red flag of the left to the city name (or districts icons:in cqui). “Insufficient amenities”.
Adding a number seems a bit redundant. What would be the purpose?

**Comment by Sorxus** [comment]
That's correct. There is a red flag when city needs amenities.
Pretty similar is with houses, there is a red flag AND house difference at the moment. 

It's just a idea, not big thing... ;)

**Comment by the-m4a** [comment]
still though, not a bad idea, considering the other 3 things already there.  since the pop growth is up top, it'd make sense to put the border growth in top left and the amenities in the bottom left, perhaps in red/yellow/green like the housing does

**Comment by Infixo** [comment]
There are several other “numbers” related to the city that are NOT visible on the banner. But that doesn’t mean they should be there.
Also, the fact that that there are 3 things, doesn’t mean that any 4th one needs to be there also.
That is why asked for the purpose.
Btw, those 3 numbers. 2 are counters - they show you when the event will happen, And you probably might do some action then, and the last (housing) is tight to the city growth, key thing to develop a city, which you also wanna monitor pretty close especially early game. And 2 of them are actually related to the key Big number - population.
Amenities are not easily managed on the city level because they are assigned automatically and distributed globally. Plus the actual number you want to propose to display is not very informative - what matters are actual percentages of bonuses / maluses it causes. Plus they don’t change very often. Plus there is already an icon for insufficient status. Plus they are loosely related to population.

If we want the utilize this 4th corner then maybe we should discuss what important and useful info is worth putting there and not just implement the first thing that comes along. Too many numbers means clutter.

**Comment by the-m4a** [comment]
true, was thinking they were tied more to a city and had an effect on the city's growth rate, and neglected to think about the regional amenities, etc.
clutter is a good point too - my last change spaced the numbers out a few pixels more just because of that crowding
