### ISSUE TITLE
"Show unit path" create problems to lens

### ISSUE THREAD

**Issue by angelolocritani** [civfanatics/CQUI_Community-Edition#94]
**Describe the bug**
When "show unit path on hover or selection" is enabled, if you open a lens and hover a unit, lens disappears and doesn't return when no longer hovering, but interfaces shows that lens is enabled.

**To Reproduce**
1. Set a unit on a long path (more than one turn)
2. Activate a lens (anyone)
3. Hover the unit with long path
4. Lens disappears
5. No longer hover - lens remains not visible

**Expected behavior**
Not sure if is intended that lens disappears; if is intended, it should return visible when no longer hovering.
Note that Religion lens has a different behavior: it seems to NOT disappear (color remains) but all other information (city religion ratio, etc) disappears.

**Screenshots**
![1_Initial](https://user-images.githubusercontent.com/67960642/87249097-6b55a900-c45d-11ea-9bb3-b017ab239808.jpg)
Initial situation

![2_Hovering](https://user-images.githubusercontent.com/67960642/87249098-6b55a900-c45d-11ea-9621-2a37a8be83ac.jpg)
Hovering on a unit (lens disappears)

![3_NoLongerHovering](https://user-images.githubusercontent.com/67960642/87249096-6a247c00-c45d-11ea-97a1-f7d1d88be1d3.jpg)
no longer hovering (lens does NOT reappear)

**General informations**
 - OS: Win
 - Version 1.0.2.39
 - Expansion: None
 - Other mods: none

**Save game and logs**
[Logs.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/4908658/Logs.zip)
[TRAIANO 325 1904 d.C..Civ6Save.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/4908661/TRAIANO.325.1904.d.C.Civ6Save.zip)

**Comment by wayneb64** [comment]
This has been there a long time. It would be nice to see this fixed. Didn't realize it was tied to showing unit path on hover. Maybe have an option to only show unit path on select as an easier work around?

**Comment by the-m4a** [comment]
I will look into this - sorry for not commenting earlier!

**Comment by the-m4a** [comment]
The specific problem is that the Active Lens is changed and never restored.  The RealizeMovementPath function is basically a copy of the Firaxis version of it, with the addition of a little bit of logic to select a unit based on the mouseover.  Under normal circumstances, the code proceeds to this section:

```
            -- Turn on lens.
            if not UILens.IsLensActive(lensNameBase) then
                UILens.SetActive(lensNameBase);
            end

```
And calls UILens.SetActive with "MovementQueue" as the value of lensNameBase.  Once this call happens, it wipes out whatever other lens is showing.

I tried a couple of things, with some success, though it's not perfect.
1. Near the beginning of _RealizeMovementPath_, call **_UILens.SaveActiveLens(),_** which basically saves off the name of whatever lens is currently applied.  In _ClearMovementPath_, call **_UILens.RestoreActiveLens()_** to restore it.  The effect is the displayed lens disappears in order to show the unit path.  It works okay for everything _except_ the Religion lens.
![Movement and Appeal Lens](https://i.imgur.com/cirCUv8.gif)

With Religion lens, it's funky:
![Movement and Religion Lens](https://i.imgur.com/5zfBlhz.gif)

2. Instead of the _UILens.SetActive_, I tried **_UILens.ToggleLayerOn(lensNameBase)_** which would not draw the dashed lines.
![Movement and ToggleLayer](https://i.imgur.com/Rz79qMo.gif)

I fiddled around with other things, but ultimately I couldn't figure out how to get the dashed lines to appear on top of the hexes as is.  Not sure it's possible, at least with the dashed lines for the lens, as opposed to coloring those hexes, or something...

(I used ScreenToGif to capture these, uploaded to Imgur as anonymous, and then inserted here using the Markdown text styling).

**Comment by Infixo** [comment]
From PR discussion. 
These lenses (movement and city mgmt) are custom made and both utilize the same layer. Enabling one disables the other.
As for now we don’t know how to enable both of them, so to avoid “blinking” and making the code even more obscure the proposed solution is to disable Movement path while City Mgmt is open.
